uploads = []
generated = []

[[outputs]]
id = "iJ6bxdm1BOYtrvPbNSLNf"
uri = "file://el-bethel-church.tar.gz"
type = "unspecified"
title = "El-Bethel Church — Upload vers public_html/ebchristianfellowship.org/"

[[outputs]]
id = "RCiMl2-DUS8qSDueQEZO_"
uri = "file://el-bethel-church.zip"
type = "unspecified"
title = "El-Bethel Church — dist.zip (upload dans ebchristianfellowship.org/)"

[[outputs]]
id = "s2jtJXvSphnkdGgNb0g8H"
uri = "file://images-only.zip"
type = "unspecified"
title = "images-only.zip — à extraire dans ebchristianfellowship.org/"

[[outputs]]
id = "7O3j3xPU8Z6rswApGmrrr"
uri = "file://artifacts/el-bethel-church/public/images-optimized.zip"
type = "unspecified"
title = "images-optimized.zip — Remplace le dossier images/ sur cPanel"

[[outputs]]
id = "6IiGs82M98Y_G_GvWdyZ2"
uri = "file://artifacts/el-bethel-church/public/el-bethel-church-final.zip"
type = "unspecified"
title = "el-bethel-church-final.zip — Site complet à uploader sur cPanel"
